# Copyright (C) 2023 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Ubuntu CI

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/ubuntu-ci.yml"
      - "cmake/**"
      - "examples/**"
      - "external/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"
    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/ubuntu-ci.yml"
      - "cmake/**"
      - "examples/**"
      - "external/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "conanfile.py"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CONAN_REVISIONS_ENABLED: "1"
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"
  CONAN_V2_MODE: "1"


defaults:
  run:
    shell: bash

jobs:
  matrix-factory:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-result.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.after }}

      - name: Detect CI type
        id: ci-type
        run: |
          if git log --format=%B -n 1 ${{ github.event.after }} | grep -qF '[ci full]'; then
            echo "type=full" >> $GITHUB_OUTPUT
          else
            echo "type=short" >> $GITHUB_OUTPUT
          fi

      - name: Generate matrix
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            // Documentation
            // https://docs.github.com/en/actions/learn-github-actions/contexts#fromjson
            // https://github.com/actions/runner/issues/982#issuecomment-809360765
            var ci_short = "${{ steps.ci-type.outputs.type }}" === "short"
            
            var includes = []
            // Debug builds (short CI)
            includes.push({ image: 'conanio/gcc8-ubuntu16.04',      build_type: 'Debug' })
            includes.push({ image: 'conanio/gcc12-ubuntu16.04',     build_type: 'Debug' })
            includes.push({ image: 'conanio/clang8',                build_type: 'Debug' })
            includes.push({ image: 'conanio/clang14-ubuntu16.04',   build_type: 'Debug' })
            // Release builds (short CI)
            includes.push({ image: 'conanio/gcc12-ubuntu16.04',     build_type: 'Release' })
            includes.push({ image: 'conanio/clang14-ubuntu16.04',   build_type: 'Release' })
            if (ci_short) {
              return { include: includes }
            }
            // Debug builds (long CI)
            includes.push({ image: 'conanio/gcc9-ubuntu16.04',      build_type: 'Debug' })
            includes.push({ image: 'conanio/gcc10-ubuntu16.04',     build_type: 'Debug' })
            includes.push({ image: 'conanio/gcc11-ubuntu16.04',     build_type: 'Debug' })
            includes.push({ image: 'conanio/gcc12-ubuntu16.04',     build_type: 'Debug' })
            includes.push({ image: 'conanio/clang9',                build_type: 'Debug' })
            includes.push({ image: 'conanio/clang10-ubuntu16.04',   build_type: 'Debug' })
            includes.push({ image: 'conanio/clang11-ubuntu16.04',   build_type: 'Debug' })
            includes.push({ image: 'conanio/clang12-ubuntu16.04',   build_type: 'Debug' })
            includes.push({ image: 'conanio/clang13-ubuntu16.04',   build_type: 'Debug' })
            includes.push({ image: 'conanio/clang14-ubuntu16.04',   build_type: 'Debug' })
            // Release builds (long CI)
            includes.push({ image: 'conanio/gcc8-ubuntu16.04',      build_type: 'Release' })
            includes.push({ image: 'conanio/gcc9-ubuntu16.04',      build_type: 'Release' })
            includes.push({ image: 'conanio/gcc10-ubuntu16.04',     build_type: 'Release' })
            includes.push({ image: 'conanio/gcc11-ubuntu16.04',     build_type: 'Release' })
            includes.push({ image: 'conanio/clang8',                build_type: 'Release' })
            includes.push({ image: 'conanio/clang9',                build_type: 'Release' })
            includes.push({ image: 'conanio/clang10-ubuntu16.04',   build_type: 'Release' })
            includes.push({ image: 'conanio/clang11-ubuntu16.04',   build_type: 'Release' })
            includes.push({ image: 'conanio/clang12-ubuntu16.04',   build_type: 'Release' })
            includes.push({ image: 'conanio/clang13-ubuntu16.04',   build_type: 'Release' })
            return { include: includes }

  build-project:
    needs: matrix-factory
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix-factory.outputs.matrix) }}

    container:
      image: ${{ matrix.image }}:1.59.0
      options: "-v ${{ github.workspace }}:${{ github.workspace }} --user=root"

    steps:
      - uses: actions/checkout@v3

      - name: Update CMake
        run: pip install --no-cache-dir 'cmake==3.26.*'

      - name: Generate cache key
        id: cache-key
        run: |
          image="${{ matrix.image }}"
          build_type="${{ matrix.build_type }}"
          hash="${{ hashFiles('conanfile.py', '.github/workflows/ubuntu-ci.yml') }}"

          echo "key=$image-$build_type-$hash" >> $GITHUB_OUTPUT

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v3
        with:
          key: conan-${{ steps.cache-key.outputs.key }}
          path: ${{ env.CONAN_USER_HOME }}

      - name: Clean Conan cache (pre-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs

      - name: Install build dependencies
        run: |
          mkdir build
          cd build
          conan install ..                 \
            --build=outdated               \
            -s compiler.cppstd=17          \
            -s compiler.libcxx=libstdc++11 \
            -s build_type=${{ matrix.build_type }}

      - name: Clean Conan cache (post-build)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: |
          conan remove -f "*" --builds
          conan remove -f "*" --src
          conan remove -f "*" --system-reqs
          conan remove -f "*" --outdated

      - name: Configure project
        run: |
          git config --global --add safe.directory ${{ github.workspace }}

          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DHICXX_ENABLE_TESTING=ON                   \
                -DHICXX_BUILD_EXAMPLES=ON                   \
                -S "${{ github.workspace }}"                \
                -B "${{ github.workspace }}/build"          \
                -DCMAKE_MODULE_PATH="${{ github.workspace }}/build/"

      - name: Build project
        run: cmake --build ${{ github.workspace }}/build -j $(nproc)

      - name: Run unit tests
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --test-dir .        \
                --schedule-random   \
                --output-on-failure \
                --no-tests=error    \
                --timeout 30        \
                -j $(nproc)

  ubuntu-ci-status-check:
    name: Status Check (Ubuntu CI)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - matrix-factory
      - build-project

    steps:
      - name: Collect job results
        if: |
          needs.matrix-factory.result != 'success' ||
          needs.build-project.result != 'success'
        run: exit 1
